# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 407a3e4f1dd4364d6ea65e17378ac1cc4ff150bfe850a90439ff518386089538f9fea6df8b2fe59621ddbf924ff504d945369fbb048fe5b7f31e8b47d67df3d5

test:
  secret_key_base: 15dd846d645110bda2a83cfb0a5179f9432f9b32804e882b03302a92ab2c67559256a1a855a16a2785dff2492d09ebf90717558d607d52ce977ba44c495cef4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
